letters:
  "796127242":
    birth_date: '19390820'
    edipi: '1005361920^NI^200DOD^USDOD^A'
    family_name: 'STEPHENS'
    gender: 'M'
    given_names: ['BRIAN', 'J']
    icn: '1008709838V592386^NI^200M^USVHA^P'
    mhv_ids: ~
    vba_corp_id: '32245561^PI^200CORP^USVBA^A'
    ssn: '796127242'
