mvi:
  url: http://ps-dev.commserv.healthevet.va.gov:8110/psim_webservice/IdMWebService
  open_timeout: 2
  timeout: 10
  mock: true
  processing_code: T
  client_cert_path: config/certs/vetsgov-localhost.crt
  client_key_path: config/certs/vetsgov-localhost.key

betamocks:
  enabled: true
  recording: false
  # cache_dir: ../vets-api-mockdata # when booting via rails; e.g. bundle exec rails s or bundle exec rails c
  cache_dir: /cache # with docker; e.g. make up or make console
  services_config: config/betamocks/services_config.yml
